// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWI0bEKVjWWehBEAMgiCUhIdVLFKpjB0',
    appId: '1:432130890665:web:05fc588365687afea382b8',
    messagingSenderId: '432130890665',
    projectId: 'testing-fe87f',
    authDomain: 'testing-fe87f.firebaseapp.com',
    storageBucket: 'testing-fe87f.firebasestorage.app',
    measurementId: 'G-6J60VPFJGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVlNEgVb63_HcnkuzNmv92fzB4l7w4Ba8',
    appId: '1:432130890665:android:8fc84a489fa78c55a382b8',
    messagingSenderId: '432130890665',
    projectId: 'testing-fe87f',
    storageBucket: 'testing-fe87f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcDhleH59JNUxyKzS0O5KwiVOz7HiaunM',
    appId: '1:432130890665:ios:06d1ed27682b4d6ea382b8',
    messagingSenderId: '432130890665',
    projectId: 'testing-fe87f',
    storageBucket: 'testing-fe87f.firebasestorage.app',
    iosBundleId: 'com.example.noteApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcDhleH59JNUxyKzS0O5KwiVOz7HiaunM',
    appId: '1:432130890665:ios:06d1ed27682b4d6ea382b8',
    messagingSenderId: '432130890665',
    projectId: 'testing-fe87f',
    storageBucket: 'testing-fe87f.firebasestorage.app',
    iosBundleId: 'com.example.noteApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMWI0bEKVjWWehBEAMgiCUhIdVLFKpjB0',
    appId: '1:432130890665:web:2cf9e0335d7e6275a382b8',
    messagingSenderId: '432130890665',
    projectId: 'testing-fe87f',
    authDomain: 'testing-fe87f.firebaseapp.com',
    storageBucket: 'testing-fe87f.firebasestorage.app',
    measurementId: 'G-WW2JWCXLXS',
  );
}
